version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: fpck
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  migration:
    image: fpck_migration:0.1
    build:
      context: ./migration
    volumes:
      - ./migration:/srv
    depends_on:
      - db
    command: alembic upgrade head

  dashboard:
    image: fpck_dashboard:0.1
    build:
      context: ./dashboard
    volumes:
      - ./dashboard:/srv
    command: npm run dev
    ports:
      - 8080:8080

volumes:
  db-data:
