version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: fpck
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  migration:
    build:
      context: ./migration
    volumes:
      - ./migration:/srv
    depends_on:
      - db
    command: alembic upgrade head

  dashboard:
    build:
      context: ./dashboard
    volumes:
      - ./dashboard:/srv
    command: npm run dev
    environment:
      - PORT=${WEBPACKPORT}
    ports:
      - ${WEBPACKPORT}:${WEBPACKPORT}

  luigi:
    build:
      context: ./app
    command: luigid
    volumes:
      - ./app:/srv
    ports:
      - ${LUIGI_PORT}:8082

  app:
    build:
      context: ./app
    volumes:
      - ./app:/srv
    depends_on:
      - luigi


volumes:
  db-data:
