version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: fpck
    ports:
      - 5432:5432

  migration:
    image: fpck_migration:0.1
    build:
      context: ./migration
    volumes:
      - ./migration:/srv
    depends_on:
      - db
