version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: fpck
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  migration:
    image: fpck_migration:0.1
    build:
      context: ./migration
    volumes:
      - ./migration:/srv
    depends_on:
      - db
    command: alembic upgrade head
volumes:
  db-data:
